import cv2
import numpy as np
import glob

# --- 1. LOAD PRE-COMPUTED RECTIFICATION DATA ---
# This file should contain the maps generated by initUndistortRectifyMap
config_path = "stereo_intrinsics/stereo_config.npz"
data = np.load(config_path)
 
map1_l = data['map1_l']
map2_l = data['map2_l']
map1_r = data['map1_r']
map2_r = data['map2_r']

print(f"Loaded rectification maps from {config_path}")

# --- 2. LOAD A TEST IMAGE PAIR ---
# Replace with your actual image paths
left_images = sorted(glob.glob("stereo_calib_9x6_30mm/left/*.jpg"))
right_images = sorted(glob.glob("stereo_calib_9x6_30mm/right/*.jpg"))

if not left_images or not right_images:
    raise FileNotFoundError("No images found in the specified folders.")

img_l = cv2.imread(left_images[0])
img_r = cv2.imread(right_images[0])

# --- 3. APPLY RECTIFICATION (REMAP) ---
# No calculation happens here, just moving pixels based on the loaded maps
rect_l = cv2.remap(img_l, map1_l, map2_l, interpolation=cv2.INTER_LINEAR)
rect_r = cv2.remap(img_r, map1_r, map2_r, interpolation=cv2.INTER_LINEAR)

# --- 4. VISUALIZATION ---
# Stack the rectified images side-by-side
canvas = np.hstack((rect_l, rect_r))

# Draw horizontal helper lines to verify alignment
# Every corresponding feature (corners, objects) must stay on the same green line
line_thickness = 1
line_color = (0, 255, 0) # Green
line_interval = 40

for y in range(0, canvas.shape[0], line_interval):
    cv2.line(canvas, (0, y), (canvas.shape[1], y), line_color, line_thickness)

# --- 5. DISPLAY ---
window_name = "Stereo Rectification Test - Horizontal Alignment"
cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
cv2.imshow(window_name, canvas)
cv2.imwrite("rectification_test_result_2.jpg", canvas)

print("Visual Check: Corresponding points in both images must lie on the same horizontal line.")
print("Press any key to exit.")
cv2.waitKey(0)
cv2.destroyAllWindows()