import cv2
import numpy as np
import glob


# --- 1. LOAD PRE-COMPUTED RECTIFICATION DATA ---
# This file should contain the maps generated by initUndistortRectifyMap
config_path = "stereo_intrinsics/stereo_config.npz"
data = np.load(config_path)

map1_l = data['map1_l']
map2_l = data['map2_l']
map1_r = data['map1_r']
map2_r = data['map2_r']

print(f"Loaded rectification maps from {config_path}")

# --- 2. LOAD A TEST IMAGE PAIR ---
# Replace with your actual image paths
left_images = sorted(glob.glob("stereo_calib_9x6_30mm/left/*.jpg"))
right_images = sorted(glob.glob("stereo_calib_9x6_30mm/right/*.jpg"))

if not left_images or not right_images:
    raise FileNotFoundError("No images found in the specified folders.")

img_l = cv2.imread(left_images[0])
img_r = cv2.imread(right_images[0])

# --- 3. APPLY RECTIFICATION (REMAP) ---
# No calculation happens here, just moving pixels based on the loaded maps
rect_l = cv2.remap(img_l, map1_l, map2_l, interpolation=cv2.INTER_LINEAR)
rect_r = cv2.remap(img_r, map1_r, map2_r, interpolation=cv2.INTER_LINEAR)


# --- 1. SETUP STEREO MATCHER ---
# These parameters are standard for starting out
block_size = 5
num_disp = 16 * 6  # Must be divisible by 16. Increase for closer objects.
min_disp = 0

stereo = cv2.StereoSGBM_create(
    minDisparity=min_disp,
    numDisparities=num_disp,
    blockSize=block_size,
    P1=8 * 3 * block_size**2,
    P2=32 * 3 * block_size**2,
    disp12MaxDiff=1,
    uniquenessRatio=10,
    speckleWindowSize=100,
    speckleRange=32,
    preFilterCap=63,
    mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY
)

# --- 2. COMPUTE DISPARITY ---
# Use the rectified images (rect_l, rect_r) from your previous step
gray_l = cv2.cvtColor(rect_l, cv2.COLOR_BGR2GRAY)
gray_r = cv2.cvtColor(rect_r, cv2.COLOR_BGR2GRAY)

disparity = stereo.compute(gray_l, gray_r)

# --- 3. NORMALIZE FOR VISUALIZATION ---
# The raw disparity is in 16.4 fixed-point format, we need to normalize it to 0-255
disp_vis = cv2.normalize(disparity, None, alpha=0, beta=255, 
                         norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)

# Apply a colormap to make it look like a heat map
disp_color = cv2.applyColorMap(disp_vis, cv2.COLORMAP_JET)

# --- 4. DISPLAY ---
cv2.imshow("Rectified Left", rect_l)
cv2.imshow("Disparity Map", disp_color)
cv2.waitKey(0)
cv2.destroyAllWindows()