import cv2
import numpy as np
import glob


# --- 1. LOAD PRE-COMPUTED RECTIFICATION DATA ---
# This file should contain the maps generated by initUndistortRectifyMap
config_path = "stereo_intrinsics/stereo_config.npz"
data = np.load(config_path)
Q = data['Q']

map1_l = data['map1_l']
map2_l = data['map2_l']
map1_r = data['map1_r']
map2_r = data['map2_r']

print(f"Loaded rectification maps from {config_path}")

# --- 2. LOAD A TEST IMAGE PAIR ---
# Replace with your actual image paths
left_images = sorted(glob.glob("stereo_calib_9x6_30mm/left/*.jpg"))
right_images = sorted(glob.glob("stereo_calib_9x6_30mm/right/*.jpg"))

if not left_images or not right_images:
    raise FileNotFoundError("No images found in the specified folders.")

img_l = cv2.imread(left_images[0])
img_r = cv2.imread(right_images[0])

# --- 3. APPLY RECTIFICATION (REMAP) ---
# No calculation happens here, just moving pixels based on the loaded maps
rect_l = cv2.remap(img_l, map1_l, map2_l, interpolation=cv2.INTER_LINEAR)
rect_r = cv2.remap(img_r, map1_r, map2_r, interpolation=cv2.INTER_LINEAR)


# --- 1. SETUP MATCHERS ---
# Left Matcher (the one you used)
block_size = 5
num_disp = 16 * 6
l_matcher = cv2.StereoSGBM_create(
    minDisparity=0,
    numDisparities=num_disp,
    blockSize=block_size,
    P1=8 * 3 * block_size**2,
    P2=32 * 3 * block_size**2,
    disp12MaxDiff=1,
    uniquenessRatio=15,    # Increased to filter noise
    speckleWindowSize=200, # Increased to remove small blobs
    speckleRange=2,
    mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY
)

# Right Matcher (required for filtering)
r_matcher = cv2.ximgproc.createRightMatcher(l_matcher)

# --- 2. SETUP WLS FILTER ---
wls_filter = cv2.ximgproc.createDisparityWLSFilter(matcher_left=l_matcher)
wls_filter.setLambda(8000.0) # Smoothness (standard: 8000)
wls_filter.setSigmaColor(1.5) # How much to follow edges (standard: 1.5)

# --- 3. COMPUTE DISPARITIES ---
gray_l = cv2.cvtColor(rect_l, cv2.COLOR_BGR2GRAY)
gray_r = cv2.cvtColor(rect_r, cv2.COLOR_BGR2GRAY)

disp_l = l_matcher.compute(gray_l, gray_r)
disp_r = r_matcher.compute(gray_r, gray_l)

# --- 4. APPLY FILTER ---
# This fills holes and removes noise based on the Left Image texture
filtered_disp = wls_filter.filter(disp_l, gray_l, disparity_map_right=disp_r)


# --- 1. CONVERT TO FLOAT AND SCALE ---
# SGBM and WLS outputs are 16x the actual disparity values
filtered_disp_float = filtered_disp.astype(np.float32) / 16.0

# --- 2. CLIP OUTLIERS ---
# We limit the disparity to the range we actually searched [0, num_disp]
# This prevents a few bad pixels from ruining the color normalization
filtered_disp_float[filtered_disp_float < 0] = 0
filtered_disp_float[filtered_disp_float > num_disp] = num_disp

# --- 3. SCALE TO 8-BIT (0-255) ---
# We map the range [0, num_disp] to [0, 255]
disp_vis = (filtered_disp_float * (255.0 / num_disp)).astype(np.uint8)

# --- 4. APPLY COLORMAP ---
# Using JET: Red = Close, Blue = Far
disp_color = cv2.applyColorMap(disp_vis, cv2.COLORMAP_JET)

# --- 5. MASK INVALID PIXELS ---
# Pixels where the matcher failed (disparity <= 0) should be black
disp_color[filtered_disp <= 0] = [0, 0, 0]

# --- 6. CROP THE MRE (Messy Rectification Edges) ---
# The left side of the left image has no matching data in the right image
# We crop it by 'num_disp' to see only valid depth data
crop_margin = int(num_disp)
final_view = disp_color[:, crop_margin:-crop_margin]

# # --- 7. DISPLAY ---
# cv2.imshow("Fixed Filtered Depth Map", final_view)
# cv2.waitKey(0)

# --- 1. RECONSTRUCT 3D POINTS ---
# Use the filtered disparity to get X, Y, Z coordinates in meters
# Q is the matrix you saved during stereoRectify
points_3d = cv2.reprojectImageTo3D(filtered_disp.astype(np.float32) / 16.0, Q)

# --- 2. MOUSE CALLBACK FUNCTION TO MEASURE DISTANCE ---
def check_distance(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        # points_3d contains (X, Y, Z) for every pixel
        point = points_3d[y, x]
        
        # Z is the depth (distance from camera plane)
        # X and Y are coordinates relative to the left camera center
        distance_z = point[2]
        
        # Calculate Euclidean distance from camera origin (0,0,0) to the point
        actual_dist = np.sqrt(np.sum(point**2))
        
        print(f"Pixel ({x}, {y}):")
        print(f"  Z (Depth): {distance_z:.3f} meters")
        print(f"  Euclidean distance: {actual_dist:.3f} meters")
        print(f"  Coordinates: X={point[0]:.2f}, Y={point[1]:.2f}, Z={point[2]:.2f}")

# --- 3. SHOW AND INTERACT ---
window_name = "Depth Measurement (Click to measure)"
cv2.namedWindow(window_name)
cv2.setMouseCallback(window_name, check_distance)

# Show the colored depth map we created in the previous step
cv2.imshow(window_name, final_view)
print("Click on any object in the depth map to see its distance in meters.")
cv2.waitKey(0)
cv2.destroyAllWindows()